finance-quote/finance-quote

lib/Finance/Quote/HU.pm
t/hu.t

Fixed BAMOSZ website scraping and download stocks directly from www.BET.hu
Tests pass with minimal modification (I used different error messages)
I have rewritten HU.pm, because it was really old and the websites it used changed significantly.
Mutual fund data is pulled from Association of Hungarian Investment Fund and Asset Management Companies (BAMOSZ), as it was done in the 2008-2009 version of HU.pm, but update to a new website layout. Mutual fund data may be searched by ISIN.
Stock data is now pulled directly from Budapest Stock Exchange (BET) instead of www.magyartokepiac.hu, because apparently Magyar Tokepiac has stopped publishing stock price data. Stock data may be searched by ticker or ISIN.
To be honest, I don't trade stocks and don't understand much about them, so the BET …

HU.pm up to date URLs and tables

---

lib/Finance/Quote.pm
lib/Finance/Quote/FidelityFixed.pm

This series of changes addes the module originally written by Peter Ratzlaff to get bond quotes from Fidelity.  I've been using it for several years and have updated it over time to keep up with changes on the Fidelity web site.  If you want I can collapse all these into one commit, or you can leave them as is to preserve the history.
The module name (fidelity_fixed) may not be the best, but that's the name it had when I got it.  Change it if you want to.

Fidelity fixed

---

lib/Finance/Quote/Tiaacref.pm

The data returned from the web site for the old fake symbols used by the TIAA/CREF module changed.  The first field is now the new symbol for the fund in question instead of the name of the fund.
Also move the test of $check{$line[0]} inside the if that makes sure that it is defined.  This avoids an error if the web site returns a value for a security we didn't ask for.

Tiaacref fixes

---

lib/Finance/Quote/AEX.pm
lib/Finance/Quote/AIAHK.pm
lib/Finance/Quote/ASEGR.pm
lib/Finance/Quote/BMONesbittBurns.pm
lib/Finance/Quote/BSERO.pm
lib/Finance/Quote/CSE.pm
lib/Finance/Quote/Cdnfundlibrary.pm
lib/Finance/Quote/Deka.pm
lib/Finance/Quote/FTPortfolios.pm
lib/Finance/Quote/FidelityFixed.pm
lib/Finance/Quote/FinanceCanada.pm
lib/Finance/Quote/Finanzpartner.pm
lib/Finance/Quote/LeRevenu.pm
lib/Finance/Quote/Morningstar.pm
lib/Finance/Quote/StockHouseCanada.pm
lib/Finance/Quote/TSP.pm
lib/Finance/Quote/Trustnet.pm
lib/Finance/Quote/VWD.pm
lib/Finance/Quote/ZA.pm
lib/Finance/Quote/ZA_UnitTrusts.pm

Hello!
Thanks for taking the time to work on Finance::Quote! This is a very simple patch to replace any uses of indirect object notation:
my $obj = new Some::Class
with the recommended Perl notation:
my $obj = Some::Class->new
Hope it helps! Thanks!

removing indirect object notation

---

t/tsx.t

Updated the securities used to test the tsx.pm module.  Some of the original symbols listed are no longer active for the securities listed in the test.  These would always show as failing the test.

Update TSX Test Stocks

---

lib/Finance/Quote.pm
lib/Finance/Quote/AlphaVantage.pm
t/alphavantage.t

Hey there, like many others I was frustrated that Yahoo shut down their stock price API this week, thus rendering `Finance::Quote::Yahoo` unusable.
In the `finance-quote-devel` mailing list, @ecocode mentioned starting work on a dedicated module for [AlphaVantage](https://www.alphavantage.co) when time became available to him. While this is far from a finished product, I hope it provides a good enough start towards getting such a module included in `Finance::Quote`.
A couple notes:
- All of the tests for AlphaVantage pass given that `ALPHAVANTAGE_API_KEY` is set in the environment.
- I have not yet tried wiring this module up to GnuCash.
- I do not know if `Finance::Quote` has any opinions on how to store configuration such as an API key. I chose to use the environment because it was easy …

[WIP] Initial pass at adding AlphaVantage module to Finance::Quote

---

lib/Finance/Quote/ASX.pm

Also add currency AUD to stocks starting with X which are not indexes. (GnuCash bug https://bugzilla.gnome.org/show_bug.cgi?id=770132 - Price editor does not find ASX:XRO)
As a side benefit, this also fixes https://rt.cpan.org/Public/Bug/Display.html?id=97551 : missing column '% Chg' (p_change).

Issue 46 Use new m.asx.com.au url as old no longer works

---

lib/Finance/Quote.pm
t/currency.t

Changes to use AlphaVantage for currency exchange rates.  The tests all seem to work, although I've had trouble running them since AlphaVantage seems  to be overloaded and timing  out frequently.

Use AlphaVantage for currency quotes now that Yahoo is gone.

---

lib/Finance/Quote/AlphaVantage.pm

Place it next to Stockholm since the entires don't appear to be sorted in any way.

AlphaVantage: add Helsinki stock exchange to currencies_by_suffix

---

lib/Finance/Quote/ASX.pm
t/asx.t

Go back to www.asx.com.au/asx/markets/priceLookup.do which now works again.
Unfortunately the following fields are no longer available (not needed for GnuCash):
date, name, div_yield, eps, pe + year_range.
There is a date available but it is always today, so this script does not return it (GnuCash gnc-fq-helper will default it to today).

Issue 80 ASX.pm m.asx.com.au no longer works

---

lib/Finance/Quote/AlphaVantage.pm

When we hit the rate limit, AlphaVantage no longer returns an `Information` field but a `Note` field, e.g.
```
{
"Note": "Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/ if you would like to target a higher API call frequency."
}
```
This broke the throttling code.

Fix AlphaVantage rate limiting

---

lib/Finance/Quote.pm
lib/Finance/Quote/YahooJSON.pm

1. MS Windows strftime() does not support %T so use equivalent %H:%M:%S instead.
2. Fix perl warnings which can cause GnuCash to hang when multiple quotes (>15) are requested.

yahooJSON.pm returns date 00/00/2000 in Windows

---

lib/Finance/Quote/YahooJSON.pm
t/yahoojson.t

Pull request 109 was a few commits behind the master, including changes to the YahooJSON.pm module. In addition, there was a syntax error in the code added to that module in the pull request.
So it can be included in the next F::Q release, I created a new branch based on recent commits and added the code for correcting the currency returned for Johannesburg Stock Exchange (JSE) securities. It was easier to reconcile the merge using a current version of the module.

Jsefix - Duplicate of Pull Request 109

---

Modules-README.yml
lib/Finance/Quote/Fidelity.pm
t/fidelity.t

- The old Fidelity link was broken, so I searched around and found the correct replacement which gives daily quotes for all Fidelity funds. 
- Some of the fields shifted around, so I updated the fields to match the new data source. One column (number) doesn't exist anymore, so I removed it (it's not needed by GnuCash).
- I updated the documentation to remove the note that this module isn't functional (since it is now functional).
- I tested that the module works with GnuCash 3.8b+ which I assume is the expected consumer of the information.
- The functionality can also be verified from a GNU cash install by running something similar to the following:
`perl gnc-fq-dump -v fidelity_direct FBGRX`

Update Fidelity Direct source to make it functional

---

lib/Finance/Quote.pm

An inverse rate of 0.0 is sometimes fetched from Alphavantage, and this change allows F::Q to gracefully handle that.

Bug fix: In the currency method, only calculate the inverse if possible.

---

lib/Finance/Quote/Currencies.pm

The fix in 9df6b3b changed the field source in the method, but not the values in the hard-coded database. This PR updates the hard-coded values as I believe they were intended to be. It also uses Unicode characters directly in the code. I don't know if this is okay within the code base, but I couldn't figure out how to replace the wide characters with their code points.
Now passes tests.

Currencies fix

---

Modules-README.yml
lib/Finance/Quote.pm
lib/Finance/Quote/XETRA.pm
t/xetra.t

Hi, I contributed a new module to fetch quotes from the [frankfurt stock exchange](https://www.xetra.com/xetra-en/), which provides a JSON endpoint. As I am new to perl, I based the module on `yahoo_json` and made the necessary modifications.
I don't know what is your policy on testing, but I can run the example script successfully:
```
$ perl stockdump.pl xetra DE000A0D8Q07
$VAR1 = {
'DE000A0D8Q07exchange' => 'XETR',
'DE000A0D8Q07high' => '35.42',
'DE000A0D8Q07date' => '09/29/2020',
'DE000A0D8Q07symbol' => 'DE000A0D8Q07',
'DE000A0D8Q07isodate' => '2020-09-29',
'DE000A0D8Q07method' => 'xetra',
'DE000A0D8Q07close' => '35.445',
'DE000A0D8Q07low' => '35.33',
'DE000A0D8Q07last' => '35.42',
'DE000A0D8Q07currency' => 'EUR',
'DE000A0D8Q07success' => 1
};
```

Fetching quotes from XETRA (Frankfurt stock exchange)

---

Modules-README.yml
dist.ini
lib/Finance/Quote/Currencies.pm
lib/Finance/Quote/Tiaacref.pm
t/tiaacref.t

Major re-write of the broken TIAA-CREF module. Greatly simplified method should be stable as long as the backing service URL remains functional. NOTE: some of these securities are available elsewhere and some are not.
Also, added a few testing dependencies that are used here and in other modules to `dist.ini`. They are now in core, but were not for very old perls which apparently are still supported by F::Q.

TIAA-CREF fix

---

lib/Finance/Quote/Currencies.pm
lib/Finance/Quote/Oslobors.pm

There is a test specifically to check for `Data::Dumper` being loaded, so these need to be removed. Possibly better just to remove the lines altogether.

Data::Dumper and debugging code (was: Misc fixes)

---

lib/Finance/Quote/DWS.pm

Extracting the table from the [DWS funds source page](https://www.deami.de/dps/ff/prices.aspx) using depth and count does not work anymore (layout change). Therefore the source dwsfunds is broken.
The fix can be as follows:
- Extraction of the table using the table id "FundsFinder_ResultTable".
- Replacing the call of the [deprecated `table_state` method](http://search.cpan.org/dist/HTML-TableExtract/lib/HTML/TableExtract.pm#DEPRECATED_METHODS) by `first_table_found()`

update parsing for changed layout on dwsfunds source page

---

lib/Finance/Quote.pm
lib/Finance/Quote/AEX.pm
lib/Finance/Quote/AlphaVantage.pm
lib/Finance/Quote/CurrencyRates/Fixer.pm
lib/Finance/Quote/CurrencyRates/OpenExchange.pm
lib/Finance/Quote/IEXCloud.pm
lib/Finance/Quote/OnVista.pm

In Debian we are currently applying the following patch to
Finance-Quote.
We thought you might be interested in it too.
Description: Fix some spelling mistakes
Origin: vendor
Author: gregor herrmann <gregoa@debian.org>
Last-Update: 2021-03-07
The patch is tracked in our Git repository at
https://salsa.debian.org/perl-team/modules/packages/libfinance-quote-perl/raw/master/debian/patches/spelling.patch
Thanks for considering,
gregor herrmann,
Debian Perl Group

Fix some spelling mistakes

---

lib/Finance/Quote/ASX.pm
lib/Finance/Quote/OnVista.pm

In Debian we are currently applying the following patch to
Finance-Quote.
We thought you might be interested in it too.
Description: fix some POD issues
Origin: vendor
Author: gregor herrmann <gregoa@debian.org>
Last-Update: 2021-03-06
The patch is tracked in our Git repository at
https://salsa.debian.org/perl-team/modules/packages/libfinance-quote-perl/raw/master/debian/patches/pod.patch
Thanks for considering,
gregor herrmann,
Debian Perl Group

fix some POD issues

---

lib/Finance/Quote/AlphaVantage.pm
t/alphavantage.t

When using online quotes in GnuCash, Toronto Stock Exchange prices for stocks like
MRT-UN.TO, HOT-UN.TO, CUF-UN.TO, PLZ-UN.TO, BPF-UN.TO are not being
populated.
This happens because in AlphaVantage these stocks are represented with
the TRT suffix (e.g. MRT-UN.TRT instead of MRT-UN.TO).
Even if MRT-UN.TRT is used as stock symbol the prices are still not populated in GnuCash because AlphaVantage.pm 
doesn't know about the TRT suffix. 
This pull request adds the TRT suffix and associates CAD to it.

Add TRT suffix to AlphaVantage

---

lib/Finance/Quote/MStaruk.pm

Problems with Morningstar UK were reported on the GnuCash mailing list. This single line change corrects the detected problem with a more specific RE.

Fix for problem with Morningstar UK screen scraper.

---

t/currency_lookup.t

The warning message highlighted in issue #189 is expected because it is testing an invalid parameter.  Added WARN signal handler in test file to hide the message in the the test output.

Suppress expected warning message in FQ test.  Resolves #189.

---

lib/Finance/Quote/CurrencyRates/AlphaVantage.pm

The AlphaVantage currency module recurses with reversed currencies
if the exchange rate is less than .001, but it forgot to actually
reverse the currencies.

Don't recurse infinitely when exchange rate is less than .001.

---

lib/Finance/Quote/Bourso.pm

Fix for issue #174. The symbol derived from parsing the HTML retrieved for some securities does not match the stock requested. Calling the store_date method with the symbol instead of $stock does not populate the correct hash.

Changed $symbol to $stock in calls to store_date

---

lib/Finance/Quote/TSP.pm

tsp.gov stopped returning fund quotes for previous URL format.

minor update to TSP url

---

Modules-README.yml
lib/Finance/Quote.pm
lib/Finance/Quote/TesouroDireto.pm
t/tesouro_direto.t

Tesouro Direto is Brazilian's National Treasury program for selling
public bounds to private investors. This module allows for the
retrieval of updated bounds value from the program's website.

Added new module TesouroDireto.pm

---

Modules-README.yml
lib/Finance/Quote/ZA.pm

Updated Sharenet parsing
Sharenet reports share prices in minor denominations. All other examples
reports in major denominations. GnuCash specifically is expecting major
denomination.
Added the following fields:
* Exchange: JSE
* Last: set to the same as price
* Source: set to sharenet.co.za
* Symbol: set to the input symbol
The only concern I have is the change in the interface in terms of major/minor denominations that may break other applications. According the wiki page only GnuCash is using this.

Changes to ZA module

---

lib/Finance/Quote/CurrencyRates/AlphaVantage.pm

AlphaVantage API [CURRENCY_EXCHANGE_RATE](https://www.alphavantage.co/documentation/#currency-exchange) seems to be available only to premium users.
This pull request is to change the code so that they can get the value even if they are not a premium user.
(Fix #229)

Use function=FX_DAILY in Finance::Quote::CurrencyRates::AlphaVantage (Fix #229)

---

lib/Finance/Quote/CurrencyRates/AlphaVantage.pm

Reverts finance-quote/finance-quote#230
AlphaVantage changed the `CURRENCY_EXCHANGE_RATE` API back to not being a premium API.

Revert "Use function=FX_DAILY in Finance::Quote::CurrencyRates::AlphaVantage (Fix #229)"

---

Modules-README.yml
lib/Finance/Quote/Fondsweb.pm
t/fondsweb.t

Fondsweb.pm failed in GnuCash because the ISIN was not retrieved correctly.
When both ISIN and WKN are present on the website, the module concatenated them. GnuCash expects the matched symbol returned, so I split the value after the 12th position.
Furthermore, I added some more test cases to fondsweb.t, and Modules-README.yml.

Update for Fondsweb.pm

---

Changes
Modules-README.yml
htdocs/index.html
lib/Finance/Quote/YahooJSON.pm

Changed https://query1.finance.yahoo.com/v7/finance/quote?symbols=PDM to https://query1.finance.yahoo.com/v6/finance/quote?symbols=PDM in lib/Finance/Quote/YahooJSON.pm
Modified Changes, Modules-README.yml, and htdocs/index.html in preparation for pushing release 1.55 to CPAN/PAUSE. Tentative release date, 05/13/2023.

Quick fix for YahooJSON.pm and minor housekeeping prep for release 1.55

---

Changes
Modules-README.yml
lib/Finance/Quote.pm
lib/Finance/Quote/MorningstarUK.pm
t/morningstarUK.t

Renamed MStarUK To be consistent with the other Morningstar modules. Kept mstaruk as a method but of course morningstaruk will use the mstaruk defined method.
Also changed symbols used for testing in morningstarUK.t, the ones formerly used were no longer traded.

MStarUK renamed to MorningstarUK

---

Changes
Modules-README.yml
lib/Finance/Quote.pm
lib/Finance/Quote/TwelveData.pm
t/twelvedata.t

Added TwelveData.pm for quotes.  Updated Changes and Modules-README.yml.
In development tree, test with
```bash
$ ONLINE_TEST=1 TEST_TWELVEDATA_API_KEY=xxx...xx dzil run prove -lv t/twelvedata.t
```
Register at https://twelvedata.com to get API key.
- Free tier limits rate to 8 quotes per minute.  This is built into the module - but if someone subscribes we don't have a way to remove rate limit.
- TwelveData can also do currency conversion, but companion Currency module not written

New module - TwelveData.pm

---

Changes
Modules-README.yml
dist.ini
lib/Finance/Quote/Fool.pm
t/fool.t

Needed to set "user-agent" to something other than LWP::UserAgent's default.
Related changes to t/fool.t, Changes, and Modules-README.yml.

Fix for Fool.pm

---

Changes
Modules-README.yml
lib/Finance/Quote/TreasuryDirect.pm
lib/Finance/Quote/TwelveData.pm

remove old perl version requirement statements. They are so old, not really relevant today.
Also removed Data::Dumper that caused another test to fail after the move of use strict;
closes #290

move use strict to be the first statement

---

Changes
Modules-README.yml
lib/Finance/Quote/IndiaMutual.pm
t/indiamutual.t

Changed IndiaMutual.pm to use IO::String object instead of downloading and parsing a file. Eliminates issues caused by incorrect or non-existing directories. Changed a non-working test case. Updated Changes and Modules-README.yml files.

Changed IndiaMutual.pm to use IO::String

---

Changes
Modules-README.yml
lib/Finance/Quote/Sinvestor.pm
lib/Finance/Quote/Tradegate.pm
lib/Finance/Quote/XETRA.pm
t/sinvestor.t
t/tradegate.t
t/xetra.t

Behaviour is exactly the same if no INST_ID is provided as parameter. This means the user can use the institute id but does not have to.

add INST_ID as optional parameter to XETRA, Tradegate and Sinvestor

---

Changes
Modules-README.yml
dist.ini
lib/Finance/Quote/YahooWeb.pm

Changed URL and added Open, High, Low, and Volume labels. Changing the URL allows parsing the trade date from the web page.

YahooWeb.pm Changes

---

Changes
Modules-README.yml
lib/Finance/Quote/AlphaVantage.pm
t/alphavantage.t

AlphaVantage does not include currency in quote data from GLOBAL_QUOTE API. With no way to  programmatically determine currency (most LSE traded symbols end in ".L"), adding ".X" to a symbol will adjust all price data by a factor of 0.01.

AlphaVantage - Currency scaling workaround

---

Changes
Modules-README.yml
README.md
lib/Finance/Quote.pm
lib/Finance/Quote/Consorsbank.pm
t/consorsbank.t

German Consorsbank has a Web API at https://www.consorsbank.de/web-financialinfo-service/api/marketdata/stocks? returning JSON data, which is used by this new module.
Their API provides quotes mostly from German exchanges, but e.g. LSE or NYSE appear for some more exotic papers.
Symbols have to be given as ISIN, German WKN or Consorsbank-internal ID.
Test:
```
$ ONLINE_TEST=1 dzil run prove -lv t/consorsbank.t
```

New module Consorsbank.pm

---

Modules-README.yml
lib/Finance/Quote/Bloomberg.pm
t/bloomberg.t

This should fix #324
The module must now use cookies to retrieve the quote data successfully. This is done using `HTTP::CookieJar::LWP`, which is a new (but small) dependency.
The module now provides the 'name' label in addition to the existing support for 'last', 'currency', 'symbol' and 'isodate'.
Conversion is also done from British pence to pounds where necessary. The associated test now includes a lookup that uses this feature.

Fix for updated Bloomberg website

---

Changes
Modules-README.yml
lib/Finance/Quote/TSP.pm

Also when the body of the response is not a CSV file. Currently not returning the `%info` hash causes issues for GnuCash.
```
my $reply = $ua->get($url, @HEADERS);
return unless ($reply->is_success);
my @line = split(/\n/, $reply->content);
return unless (@line > 1);
```

TSP.pm - Fix returns for when HTTP GET fails

---

Changes
Modules-README.yml
lib/Finance/Quote/YahooWeb.pm

The YahooWeb interface sometimes returns tables that have rows with no prices.  Skip them and find the first row with prices. One security that shows this problem is TILIX.

Skip rows in price table that don't have prices

---

Changes
Modules-README.yml
lib/Finance/Quote/Stooq.pm

1) Currencies:
+EUR, HKD, HUF, JPY, USX
-ZAR (as unused)
2) Fix for commodities traded in:
- <span>$/</span>bbl, <span>$</span>/gal, <span>$</span>/t or <span>$</span>/mmBtu for energy commodities
- $/ozt, ¢/ozt or ¢/lb for metals
- ¢/bu or ¢/lb for grains
- $/t or ¢/lb for softs
- ¢/lb for fibers
- €/t for CO2 emission
and which don't have a currency A tag, thus no href attribute.

New currencies in Stooq.pm

---

Changes
Modules-README.yml
lib/Finance/Quote/Finanzpartner.pm
t/finanzpartner.t

The parsing of Finanzpartner page sometimes fails because the current parser only works if the current quote is less than the previous day's quote.  This fix checks for both cases and uses the correct value.

Fix scraper in Finanzpartner.pm

---

Changes
Modules-README.yml
lib/Finance/Quote/Sinvestor.pm
lib/Finance/Quote/Tradegate.pm
lib/Finance/Quote/XETRA.pm
t/tradegate.t
t/xetra.t

Fixed XETRA, Tradegate and SInvestor after webpage was restructured

---

Changes
Modules-README.yml
lib/Finance/Quote/TwelveData.pm

Hash returned by TwelveData.pm did not return `last` or `price` and would not be used by GnuCash. Added `last` (copy of `close`) to data returned.

Minor change to TwelveData.pm - Add "last"

---

Changes
Modules-README.yml
README.md
lib/Finance/Quote/AlphaVantage.pm
lib/Finance/Quote/YahooJSON.pm
t/alphavantage.t

This PR removes throttling in the AlphaVantage.pm module. While AlphaVantage now limits the free API usage to 25 per day, there is no throttling enforced. 
Additionally, the number of symbols checked in the `t/alphavantage.t` test script has been reduced to 9.

AlphaVantage - Remove Throttling

---

Changes
Modules-README.yml
lib/Finance/Quote/BSEIndia.pm
lib/Finance/Quote/NSEIndia.pm

**NSEIndia.pm** is an existing Perl module in Finance::Quotes. It retrieves stocks / securities prices from the NSE India website at https://www.nseindia.com.
**BSEIndia.pm** is an existing Perl module in Finance::Quotes. It retrieves stocks prices from the BSE India website at https://www.bseindia.com.
Change in the URL of the data file and it's format to UDiFF broke quotes updates from NSEIndia.pm and BSEIndia.pm.
Issue #410 was logged due to the **NSEIndia.pm** CSV file format being changed. This change resolves the Issue #410 that impacted NSEIndia.pm. The change was to the folder, the file and the format of the contents of the CSV file released daily by nseindia.com.
It was found that Issue #410 also impacted **BSEIndia.pm**. This change resolves Issue #410 in BSEIndia.pm also.The …

Fixes #410 (NSEIndia.pm and BSEIndia.pm) - Pull Request

---

Changes
Modules-README.yml
lib/Finance/Quote.pm
lib/Finance/Quote/FinanceAPI.pm
t/financeapi.t

FinanceAPI.pm is new module. See https://financeapi.net/. An API Key is required. The URL used by the `financeapi` method is https://yfapi.net/v6/finance/quote?. 
Data is available from US and other exchanges. The free basic API Key allows 100 queries per day rate limited to 300 per minute.
It provides for the multiple/failover methods "nyse", "nasdaq", and "usa".

FinanceAPI.pm - New Module

---

Changes
Modules-README.yml
lib/Finance/Quote/TesouroDireto.pm
t/tesouro_direto.t

As the official site https://tesourodireto.gov.br started using CloudFlare, switch to an (unofficial) mirror of the bound data hosted on github as data source.
Updated the test file from a bound due on 2026 to another due on 2031 to delay having to change it later.

Fix TesouroDireto module

---

Changes
Modules-README.yml
lib/Finance/Quote/CurrencyRates/Fixer.pm
lib/Finance/Quote/CurrencyRates/OpenExchange.pm

Currency Rate modules Fixer.pm and OpenExchange.pm only allowed API_KEYs passed as arguments. This pull request allows the keys to be read from environment variables.
Fixer.pm - FIXER_API_KEY
OpenExchange.pm - OPENEXCHANGE_API_KEY
This PR resolves #426.

Allow API_KEYs from Environment Variables in Fixer.pm and OpenExchange.pm

---

Changes
Modules-README.yml
lib/Finance/Quote.pm
lib/Finance/Quote/CurrencyRates/FinanceAPI.pm
t/currency.t

New Currency Rates module.
Requires API KEY from https://financeapi.net.
Key can be passed in via argument or FINANCEAPI_API_KEY environment variable.
Merging this PR will close #427.

Added FinanceAPI Currency Rates Module

---

Changes
Modules-README.yml
lib/Finance/Quote/YahooJSON.pm

JSON field `trailingAnnualDividendYield` for some securities contains "nan" instead of being null or 0.

Updated YahooJSON to validate dividend yield.

---

Modules-README.yml

Updates to formatting mostly to satisfy linters and code heightlight in my Emacs as well as to let tools like `yq` to parse the document.
Also commented on `oslocors` failure.

Update Modules-README.yml: formatting and comment on oslobors failure

---

Changes
Modules-README.yml
lib/Finance/Quote/GoogleWeb.pm

With the recent and repeated problems with YahooJson, I think the GoogleWeb option is becoming more and more viable and valuable. Here's a very small tweak for it to handle stock traded in the Hong Kong Stock Exchange (HKEX), with ticket symbols such as "2828", "0700", etc.
The logic today is to fetch from a Google Finance web URL for a ticker such as "TSLA", and then find an "A" anchor in the format of something like "TSLA:NASDAQ" and then fetch that page. There is a limited set of "exchanges" that are supported there, and I just added "HKG". I'm sure there are others (like Toronto TSX, London LON, etc.), if the reviewer(s) are willing, please feel free to add those too.
Thank you for the good work!

Adding Hong Kong stock support to GoogleWeb

---

Changes
Modules-README.yml
lib/Finance/Quote/Comdirect.pm
t/comdirect.t

improves the Comdirect module:
- fix ETF search support
- add label `time`, `p_change`, `ask`, `bid`, `wkn`, `exchange` 
- a new label `exchanges` contains the list of available marketplaces
- the marketplace can be selected using the 'EXCHANGE' feature. This feature is already under development for other modules.
Update 2025-03-16:
- fix encoding
- i.e.: CH0038863350 name: Nestl**é**

Comdirect: add etf, more labels and EXCHANGE feature

---

Changes
Modules-README.yml
lib/Finance/Quote/AlphaVantage.pm

I recently discovered that when a symbol is not found from AlphaVantage, the JSON returned is
```
{
"Global Quote": {}
}
```
The modules sets success to "1" even though no price data is included in the returned hash.
This change checks that the "Global Quote" JSON structure contains the `"01. symbol": ...` field, otherwise it sets success to "0", and errormsg to "symbol ... not found."

Added 'symbol not found' message to AlphaVantage.pm

---

Changes
Modules-README.yml
lib/Finance/Quote/TesouroDireto.pm

Using official Tesouro Direto URL (www.tesourodireto.com.br) instead of taking the JSON from raw.githubusercontent.com that, being a copy, may be outdated

Using official Tesouro Direto URL (www.tesourodireto.com.br)

---

lib/Finance/Quote/SwissFundData.pm

Corrected minor syntax errors in original PR #515.
Line 54: `out $METHODHASH` to `our $METHODHASH`
Line 162: `{eurodate => $date)` to `{eurodate => $date}`

Correct syntax errors in SwissFundData.pm
