- lib/Finance/Quote/DWS.pm
- lib/Finance/Quote/Deka.pm
- lib/Finance/Quote/GoldMoney.pm
- lib/Finance/Quote/Tiaacref.pm
This is what the Crypt::SSLeay module itself proposes to do.
> Switch to LWP::Protocol::https instead of Crypt::SSLeay

- lib/Finance/Quote/USFedBonds.pm
Corrected the US Treasury URL
Added in a mapping from EE to N per their documentation
Set the last value to be equal to price
> Updated the USFedBonds module

- Documentation/README
Minor fix.  Update the git repo link in Documentation/README.
> Fix git repo location in Documentation/README

- Changes
- lib/Finance/Quote/AlphaVantage.pm
- t/alphavantage.t
Caveat: I haven't tested the changes to the test file.
> Add currency for Toronto (Canada) market.

- lib/Finance/Quote/AlphaVantage.pm
This is a trivial change to catch an error from the  AlphaVantage server (which keeps returning 503  errors for me).
> Check for error return from server.

- lib/Finance/Quote/AlphaVantage.pm
Fix for Issue https://github.com/finance-quote/finance-quote/issues/83
1. Retry up to 4 times if fails with Information message with a 20 second wait between tries
2. Add 1 second sleep after each API call to share server resources as recommended by Alpha Vantage
> Fq iss83 alpha vantage : Retry up to 4 times if fails with Information message

- lib/Finance/Quote.pm
- lib/Finance/Quote/AlphaVantage.pm
This PR contains the previous changes by goodvibes2 and an additional change to add a similar retry to the code in QUote.pm which uses AlphaVantage to get currency exchange rates.
> Retry AlphaVantage currency quotes up to 5 times

- lib/Finance/Quote/IndiaMutual.pm
- t/indiamutual.t
The URL update makes indiamutual work again.
The new csv updated the position of date field.
Test file fixes (if it's still being used).
> Update IndiaMutual URL, csv format

- Documentation/FAQ
Of course the essay is ancient but I guess it is still intereting.
> FAQ: tpj.com R.I.P, point to draft online

- lib/Finance/Quote.pm
- lib/Finance/Quote/MorningstarAU.pm
- t/aufunds.t
- t/morningstarau.t
As per issue #112 have forked and branched to add support for Morningstar AU fund quotation retrieval.
> Add Morningstar AU fund quotation retrieval

- lib/Finance/Quote/TSP.pm
TSP Price table now at different URL.
> update TSP url

- lib/Finance/Quote.pm
- lib/Finance/Quote/MorningstarCH.pm
- t/morningstarCH.t
I needed quotes for a fund that was only available on morningstar.ch, so I created this file, based on MStaruk.pm. I'd appreciate it if you included it, and I'm happy to respond to comments.
> feat: add support for retrieving quotes from morningstar.ch

- lib/Finance/Quote.pm
- lib/Finance/Quote/IEXTrading.pm
- t/iextrading.t
Use IEXTrading.com API to fetch quotes for US stocks.
> Add support for IEXTrading.com

- lib/Finance/Quote/FTfunds.pm
FTfunds hasn't been working for a long time since their website changed. I made this change in November 2017 and never got round to submitting it but it still works for me. There are a couple of outstanding issues on CPAN (129586, 129587) that could be cleared by including this change.
> FTfunds updated to current website

- README.md
For issue #135. Made some changes to the INSTALLATION section, including removal of the reference to the currently non-existent INSTALL file.
> Modified INSTALLATION section of README.md.

- Modules-README.yml
- lib/Finance/Quote.pm
- lib/Finance/Quote/Oslobors.pm
- t/oslobors.t
This enables quotes from oslobors.no. The quotes are gathered from a
clean JSON source that is used internally by the (Angular-based)
website.
Provides a price, date, currency and p_change.
> New mutual funds source: Oslo stock exchange

- lib/Finance/Quote.pm
- lib/Finance/Quote/AlphaVantage.pm
Commit d392bbec missed a few places where Information needed to be
changed to Note.
> Rest of fix for AlphaVantage rate limiting.

- lib/Finance/Quote/Deka.pm
The CSV data format has changed it is now:
ISIN;Fondsname;Abrechnungsdatum;Datum_Vortag;Ruecknahmepreis;Ruecknahmepreis_VT;Ausgabepreis;ADDI;Waehrung
Translated this means:
symbol;name;date;date from previous day;price;price from the previous date;issue price;ADDI (seems to be always empty);currency
> Adapted Deka CSV format

- lib/Finance/Quote/AEX.pm
- lib/Finance/Quote/AIAHK.pm
- lib/Finance/Quote/ASEGR.pm
- lib/Finance/Quote/BMONesbittBurns.pm
- lib/Finance/Quote/BSERO.pm
- lib/Finance/Quote/Bourso.pm
- lib/Finance/Quote/CSE.pm
- lib/Finance/Quote/FidelityFixed.pm
- lib/Finance/Quote/LeRevenu.pm
- lib/Finance/Quote/TSP.pm
- lib/Finance/Quote/USFedBonds.pm
forwarding a patch to the Debian package by gregoa
> Fix whatis entries of several manpages

- .gitignore
- Documentation/Hackers-Guide
- README.md
- lib/Finance/Quote.pm
- lib/Finance/Quote/IEXCloud.pm
- new-API-notes.txt
- t/fq-class-methods.t
- t/fq-object-methods.t
- t/iexcloud.t
Would like to discuss moving forward with merging the Finance::Quote API changes that include:
1. Adding optional module key to new() constructor so caller can pass API keys or other module specific parameters
1. Standardizing get/set methods
If we agree on the API changes, will still need to 
1.  updating the POD documentation for Quote.pm
1. enabling AlphaVantage to use the module specific data as another source for its API key
> FQ API improvements - Merge new-new branch into master

- lib/Finance/Quote/AlphaVantage.pm
- t/alphavantage.t
Fixes a bug in the test for empty results which caused one test failure.
Removes or replaces several symbols in the test suite that no longer seem to be available via AlphaVantage.
Tests now pass.
> AlphaVantage fix

- Modules-README.yml
- lib/Finance/Quote.pm
- lib/Finance/Quote/Fundata.pm
- t/fundata.t
Creating new Fundata module which pulls Canadian mutual fund information from: http://www.fundata.com
> Changes for new Fundata module.

- lib/Finance/Quote.pm
- lib/Finance/Quote/Bloomberg.pm
This will allow download of prices from the www.bloomberg.com website.
> Add support for Bloomberg

- Modules-README.yml
- lib/Finance/Quote/Troweprice.pm
- t/troweprice.t
Fixes and updates T. Rowe Price module (broken data source).
I confirmed that all securities returned by this data source are also found in YahooJSON. The direct data source also does not return rich information -- only date and last price. Perhaps it would be a candidate for deprecation.
> Troweprice fix

- lib/Finance/Quote/SEB.pm
The old domain taz.vv.sebank.se does no longer resolve
> Update URL to SEB funds

- lib/Finance/Quote/XETRA.pm
Hello! Seems like they changed the API endpoint so I updated the URL. I also introduced a callback to read until the first newline since they are not guaranteed to send it all at once.
> New xetra url and more resilient reading of data

- lib/Finance/Quote/BSERO.pm
Description:
The former link to obtain the info is no longer valid. Also, since the
bvb site no longer accesible using the perl python, I changed the
source to Tradeville.
> Changed source for BVB exchange

- lib/Finance/Quote.pm
- lib/Finance/Quote/Fondsweb.pm
- t/fondsweb.t
Hello,
I have add a module to catch data from Fondsweb (https://www.fondsweb.com)
Could you all review my code?
Thank you.
> Adding module for fondsweb.com (Germany)

- Changes
- dist.ini
Changes to dist.ini and Changes for upcoming v1.50 release.
> Changes related to preparing for pushing v1.50 to CPAN.

- Documentation/Release.md
- Documentation/Release.txt
- htdocs/index.html
Converting Documents/Release.txt to markdown file Documents/Release.md. Rearranged some steps and added detail.
> Minor file changes in preparation for v1.50 release to CPAN

- Modules-README.yml
A few minor updates in preparation of releasing v1.50
> Changes to Modules-README.yml

- t/fq-object-methods.t
Proposed alternate solution from #177.
> Guarding online tests

- Changes
- htdocs/index.html
Changes in preparation for pushing v1.51 to CPAN/PAUSE and SourceForge project page.
> Updated Changes and htdocs/index.html

- lib/Finance/Quote.pm
Pull request to address #197.
Minor change to logic for -defaults.
> Fixed logic for -default option

- lib/Finance/Quote/Bloomberg.pm
bloomberg html class update to correct /html parse/ errors
> Update Bloomberg class names

- Modules-README.yml
- Modules-README.yml~
- lib/Finance/Quote.pm
- lib/Finance/Quote/MorningstarCH.pm
- t/morningstarCH.t
Please include morningstar.ch again - all that's needed is the HTTPS URLs instead of the HTTP URLs.
> Re-enable morningstar.ch.

- Documentation/Hackers-Guide
- htdocs/developer.html
- htdocs/discussion.html
- htdocs/documentation.html
- htdocs/download.html
- htdocs/index.html
I wanted to clean up SourceForge HTML files that contained stale links.
I already pushed them to SF (http://finance-quote.sourceforge.net/).
While I likely didn't find all the bad links, I think I addressed the main ones.
> SourceForge Website HTML files

- Changes
- Modules-README.yml
- lib/Finance/Quote/TSP.pm
Site seems to have stabilized and this pull request reflects that latest working version.
> TSP - update URL, update handling of dates

- Changes
- Modules-README.yml
- lib/Finance/Quote/Union.pm
- t/union.t
See https://github.com/finance-quote/finance-quote/issues/226 for discussion.
> Update for Union.pm

- dist.ini
- lib/Finance/Quote/Union.pm
Also removed fixed VERSION in lib/Finance/Quote/Union.pm.
> Fixed LWP::UserAgent requirement in dist.ini.

- Changes
- dist.ini
- htdocs/index.html
Minor changes to Changes, dist.ini, and htdocs/index.html in preparation for v1.53 release.
> Housekeeping for v1.53 release

- Changes
- Modules-README.yml
- htdocs/index.html
Updates to htdocs/index.html and Changes preparing for release.
> Pre-release Housekeeping

- Changes
- Modules-README.yml
- lib/Finance/Quote/MorningstarJP.pm
> URL change in MorningstarJP.pm

- Documentation/README
- Modules-README.yml
- dist.ini
- lib/Finance/Quote.pm
- Made changes to POD in Quote.pm.
- Changed Yahoo URL in Modules-README.yml
- Uncommented Readme lines in dist.ini
- Update to Documentation/README
> Minor documentation changes and dist.ini

- Changes
- Modules-README.yml
- dist.ini
- lib/Finance/Quote.pm
Minor changes to
- Changes
- Modules-README.yml
- dist.ini
- lib/Finance/Quote.pm
> Miscellaneous minor changes

- Changes
- Modules-README.yml
- lib/Finance/Quote/Bourso.pm
- t/bourso.t
Added test case for space in quote value and added substitution operators to squash anything but numbers and period '.' in anything that has a money value.
> Fix for Issue 278

- Changes
- Modules-README.yml
- lib/Finance/Quote/CurrencyRates/YahooJSON.pm
- lib/Finance/Quote/YahooJSON.pm
Updating YahooJSON.pm to use https://query2.finance.yahoo.com/v11
> Fix for issue #282 "yahoo_json issue resurfaced" 

- Changes
- Modules-README.yml
- lib/Finance/Quote/AEX.pm
Changed web scrape process to extract date.
Fixes Fixes finance-quote/finance-quote#298
> AEX - Fix for Issue #298

- Changes
- Modules-README.yml
- lib/Finance/Quote.pm
- lib/Finance/Quote/BVB.pm
- lib/Finance/Quote/MarketWatch.pm
- t/marketwatch.t
New module gets basic data from https://www.marketwatch.com/.
> MarketWatch

- Modules-README.yml
- lib/Finance/Quote.pm
- lib/Finance/Quote/YahooWeb.pm
- t/yahooweb.t
Pulling data from a Yahoo Finance Web page is delicate.  Here is an initial implementation, but there are questions/limitations:
- What does "last" mean?  I have it pulling the value that appears on the left side under the security name, which is the current price during the day and close price in the evening/weekend.  Should last really be the extending trading price shown on the right side?
- Some of the values are not contained in descriptive HTML tags, so there is best effort to capture the correct value, but it is fragile.  However, there is no validation in the current implementation, so we could return garbage without error.
- The date is set to "day of request" and not pulled from the page.  During the trading week (at least) there is no obvious date field to use.  Not sure …
> Initial version of YahooWeb module

- Changes
- Modules-README.yml
- lib/Finance/Quote.pm
- lib/Finance/Quote/GoogleWeb.pm
- t/googleweb.t
Web scraping of https://www.google.com/finance/quote/<symbol>:<exchange>
> GoogleWeb Module

- Changes
- Modules-README.yml
- lib/Finance/Quote/Sinvestor.pm
- lib/Finance/Quote/Tradegate.pm
- lib/Finance/Quote/XETRA.pm
- t/sinvestor.t
- t/tradegate.t
- t/xetra.t
- close, change and p_change added
- bug fixed for values above 999.9 (1.000,0 converted to 1000.0)
> sinvestor pages enhanced by close, change, p_change

- Changes
- Modules-README.yml
- lib/Finance/Quote/YahooJSON.pm
Fixed setting exchange in YahooJSON.pm
> Corrected setting exchange in YahooJSON

- lib/Finance/Quote.pm
This will be temporary. Adds an LWP::UserAgent fetch for a simple counter based on web log events.
> Added count kludge to Quote.pm

- Changes
- Modules-README.yml
- lib/Finance/Quote/AlphaVantage.pm
Fixes logic for checking JSON returned.
> AlphaVantage.pm Fixed check for "Information" JSON

- lib/Finance/Quote/AlphaVantage.pm
Correct mistake when PR #328 accidentally removed changes introduced in PR #326.
> Added back changes from eb4fd6e

- Changes
- htdocs/index.html
Confirming Changes, Modules-README.yml, and others. Update to htdocs/index.html.
> Changes preparing for v1.58

- Changes
- Modules-README.yml
- lib/Finance/Quote/BSEIndia.pm
- t/bseindia.t
Actually changed to use Smart::Comments
> BSEIndia.pm - removed print for symbol not found

- Changes
- Modules-README.yml
- lib/Finance/Quote/GoogleWeb.pm
Added Mutual Funds. Minor update to POD.
> GoogleWeb.pm Update

- Changes
- Modules-README.yml
- lib/Finance/Quote.pm
- lib/Finance/Quote/GoogleWeb.pm
- t/googleweb.t
Added BATS exchange to GoogleWeb.pm. Closing #355.
> Added BATS to GoogleWeb. Disabled Fidelity.pm

- Changes
- Modules-README.yml
- lib/Finance/Quote/BSEIndia.pm
- lib/Finance/Quote/IndiaMutual.pm
IndiaMutual.pm & BSEIndia.pm are existing Perl modules in Finance::Quotes
IndiaMutual.pm gets end of day NAVs (net asset values) from the [AMFI India](https://www.amfiindia.com/) web site
BSEIndia.pm gets daily bhav copy stock quotes from the [BSE India](https://www.bseindia.com) web site
Indian Mutual Funds NAVs were retrieved by mirroring the file NAVAll.txt from the URL https://www.amfiindia.com/spages/NAVAll.txt into a temporary folder. This change eliminates the need to use a temporary folder by loading the contents of NAVAll.txt into a memory variable instead of mirroring the file to temporary folder.
BSE India stock quotes were retrieved by mirroring the daily bhav copy file using the earlier data format from URL https://www.bseindia.com/download/BhavCopy/Equity/EQ_ISINCODE_{DDMMYY} …
> Update to module IndiaMutual.pm & BSEIndia.pm. Eliminate need for temporary folder. Use standardised data file in BSEIndia.pm.

- Changes
- Modules-README.yml
- lib/Finance/Quote/NSEIndia.pm
- t/nseindia.t
NSEIndia.pm is an existing Perl module in Finance::Quotes. It retrieves stocks / securities prices from the NSE India website at https://www.nseindia.com.
The NSEIndia.pm module retrieves stocks / securities quotes by mirroring the daily bhav copy file from the NSE to a temporary folder on the local computer. This change eliminates the need to use a temporary folder by loading contents of the daily bhav copy file into a memory variable instead of mirroring the file to temporary folder.
NSEIndia.pm module is Perl code that aligns with [Finance::Quote hackers guide](https://github.com/finance-quote/finance-quote/blob/master/Documentation/Hackers-Guide). Code editor of choice was Geany on Linux which is available at https://www.geany.org/. vscode can be used too, but why use something much …
> NSEIndia.pm - Eliminated need to use temporary folder by storing data from URL into variable

- Changes
- Modules-README.yml
- lib/Finance/Quote/Bloomberg.pm
- t/bloomberg.t
> Fix Bloomberg module, now extracting data from JSON blob embedded in the HTML

- CONTRIBUTING.pod
Added `CONTRIBUTING.pod`. Related updates to `dist.ini`.
Will continue to update over the next few releases, `CONTRIBUTING.pod` will replace the "Hacker's Guide" in the Documentation folder.
Closes #311.
> Contributing POD

- .github/workflows/ci.yml
- Changes
- Modules-README.yml
- dist.ini
- lib/Finance/Quote/CurrencyRates/YahooJSON.pm
- lib/Finance/Quote/YahooJSON.pm
Added Kalpesh Patel's update to YahooJSON.pm.
Changed the YahooJSON.pm currency module to use the v8 (https://query1.finance.yahoo.com/v8/finance/chart/...=X?metrics=high&interval=1d&range=1d) API.
> Yahoo v11 Fixes

- Changes
- Modules-README.yml
- htdocs/index.html
- lib/Finance/Quote/SIX.pm
- lib/Finance/Quote/YahooJSON.pm
Fix to YahooJSON.pm module to enable UE based users to retrieve stock quotes.
This fixes #373.
> Add additional URL fetch to YahooJSON.pm

- Changes
- Modules-README.yml
- dist.ini
- lib/Finance/Quote/YahooWeb.pm
Page returned from Yahoo changed considerably. Rewrote to account for those changes. 
The current page contains JSON, so logic was changed to grab data using JSON instead of HTML::Element.
This fixes #377.
> YahooWeb Fixes

- Changes
- Modules-README.yml
- dist.ini
- lib/Finance/Quote/YahooJSON.pm
- t/yahoojson.t
Updated yahooJSON.pm to handle EU consent in robust way which dovetails into getting proper cookies and corresponding crumb to auth correctly.
> Updated yahooJSON.pm to handle EU consent in robust way.

- Changes
- Modules-README.yml
- lib/Finance/Quote.pm
- lib/Finance/Quote/StockData.pm
- t/stockdata.t
StockData.pm (https://www.stockdata.org/ has an API for US securities quote data (and Crypto/Forex). Free API allows 100 requests per day.
> New Module - StockData.pm

- Changes
- Modules-README.yml
- lib/Finance/Quote.pm
- lib/Finance/Quote/Fool.pm
- t/fool.t
Add a rewritten Fool.pm module back into Finance::Quote.
This will resolve #379.
> Restore Fool.pm

- Changes
- Modules-README.yml
- dist.ini
- lib/Finance/Quote/MarketWatch.pm
Fixed the MarketWatch.pm module.
Resolves #389.
> MarketWatch Fix

- Changes
- Modules-README.yml
- dist.ini
- lib/Finance/Quote/YahooJSON.pm
Added more error handling to capture failures from URL requests to get cookies and crumb. This would resolve #390.
> YahooJSON.pm

- htdocs/index.html
- lib/Finance/Quote.pm
Minor changes before releasing v1.62.
> Pre-Release Housekeeping v1.62 

- Modules-README.yml
Comdirect.pm and OnVista.pm were missing from Modules-README.yml.
> Add Comdirect.pm and OnVista.pm to Modules-README.yml

- Changes
- Modules-README.yml
- lib/Finance/Quote/BVB.pm
- t/bvb.t
BVB.pm is an existing Perl module in Finance::Quotes. It retrieves stocks / securities prices from BVB.ro website at https://bvb.ro.
Issue #409 was logged due to a change in the page of BVB.ro that broke quotes retrieval. This change resolves the Issue #409. Instead of retrieving stock quotes from the web page at BVB, this module now retrieves stock quotes from the daily historical stock quote data of BVB which is in the CSV format.
The finance-quote repository was forked to https://github.com/bgr22112/finance-quote
BVB.pm
- The module was a complete rewrite.
- URL of daily quotes file is https://bvb.ro/TradingAndStatistics/Trading/HistoricalTradingInfo.ashx?day=20240809
- Users can use ISIN as security code.
bvb.t
- Testing modified for end of day historical quotes download data. …
> Fixes #409. Modified BVB.pm which now uses historical quote file.

- Changes
- Modules-README.yml
- lib/Finance/Quote/Bourso.pm
Changes to Bourso.pm to fix #417.
Added methodinfo subroutine that combines labels and methods.
Changes and Modules-README.yml updated to reflect changes.
> Updated Bourso.pm to address #417.

- Changes
- Modules-README.yml
- dist.ini
- lib/Finance/Quote.pm
- lib/Finance/Quote/OnVista.pm
- t/02-pod-coverage.t
- t/onvista.t
Completely rewrote OnVista.pm. 
Related changes to Changes, Modules-README.yml, t/onvista.t.
Unrelated minor changes to dist.ini, t/01-pod.t and t/02-pod-coverage.t.
Fixes #414.
> Rewrite of OnVista.pm

- Changes
- Modules-README.yml
- lib/Finance/Quote.pm
- lib/Finance/Quote/Comdirect.pm
- t/comdirect.t
Changes to Comdirect.pm. Fixes #413.
> Comdirect.pm Changes to Fix Issue #413

- Modules-README.yml
- lib/Finance/Quote/Comdirect.pm
- t/comdirect.t
Comdirect made more changes to the website after merging the last pull request. This fixes #413 again.
> Comdirect.pm 

- Changes
- Modules-README.yml
- lib/Finance/Quote/CSE.pm
- t/cse.t
I started working on `CSE.pm` believing it has been broken - as per `Modules-README.yml`. However, it seems it's been OK all along. I took a liberty to list all fetched fields (and add a few more, that are received in a JSON data). Also updated tests to include 4 biggest companies in the exchange - hopefully, these won't disappear too fast.
> Update CSE.pm - add more labels and update Modules-README.yml

- Changes
- Modules-README.yml
- lib/Finance/Quote/Stooq.pm
Update to Stooq.pm to fix #445.
> Stooq.pm Fix

- Changes
- Modules-README.yml
- lib/Finance/Quote/AlphaVantage.pm
Fixed bad check for "Global Quote" in JSON.
This PR resolves #447.
> Update to AlphaVantage.pm for Issue #447

- htdocs/index.html
> Added release date for v1.64 to htdocs/index.html

- Changes
- Modules-README.yml
- lib/Finance/Quote/MorningstarJP.pm
- t/morningstarJP.t
I took a liberty and rewritten the module to use XML and support new metadata. Unit tests I didn't change beside adding the fund names and updating line endings to unix style.
fixes #443
> [MorningstarJP] Use XML from apl.wealthadvisor.jp

- Changes
- Modules-README.yml
- lib/Finance/Quote/Fool.pm
> Minor fixes to Fool.pm

- Changes
- Modules-README.yml
- lib/Finance/Quote/XETRA.pm
Changes to XETRA.pm. Fixes #460 
Also added `methodinfo` hash.
> Fixed XETRA.pm - Issue #460

- Changes
- Modules-README.yml
- lib/Finance/Quote/AEX.pm
- t/aex.t
This PR improves the AEX module:
- add label `exchange`, `close`, `time`
>  Improve AEX (exchange, close, time)

- Changes
- Modules-README.yml
- lib/Finance/Quote/YahooJSON.pm
- t/aex.t
Changed UserAgent header value. Fixes #467.
> YahooJSON Fix

- Changes
- Modules-README.yml
- lib/Finance/Quote/YahooWeb.pm
Also added methodinfo hash.
Fixes #468.
> YahooWeb.pm - malformed character - Issue #468

- Changes
- Modules-README.yml
- lib/Finance/Quote/YahooJSON.pm
> Adjust all currency fields for currency change.

- Changes
- Modules-README.yml
- lib/Finance/Quote/Union.pm
Added ssl_opts to User Agent to account for bad certificate chain returned from website.
Also added methodinfo hash.
Fixes #482
> Union - unionfunds

- Modules-README.yml
- lib/Finance/Quote/TwelveData.pm
Added methodinfo hash to TwelveData.pm.
Checked that throttling was enabled.
> Added methodinfo hash to TwelveData.pm

- Changes
- Modules-README.yml
- lib/Finance/Quote/CurrencyRates/CurrencyFreaks.pm
Modified CurrencyFreaks to return from and to values instead of calculated rate.
> Currency freaks

- dist.ini
- htdocs/index.html
Housekeeping before v.166 release.
> Release1.66

- Changes
- Modules-README.yml
- lib/Finance/Quote/BorsaItaliana.pm
- lib/Finance/Quote/MarketWatch.pm
- t/borsa_italiana.t
Added methodinfo() to BorsaItaliana.pm and MarketWatch.pm
> Methodinfo

- dist.ini
- lib/Finance/Quote.pm
Moved a few modules from test pre-reqs to pre-reqs
> Modified dist.ini for issue #514

- Modules-README.yml
- lib/Finance/Quote/BSEIndia.pm
- lib/Finance/Quote/BVB.pm
- lib/Finance/Quote/Deka.pm
- lib/Finance/Quote/Finanzpartner.pm
- lib/Finance/Quote/Fondsweb.pm
Added the methodinfo() subroutine to a handful of modules.
> Add methodinfo

- CONTRIBUTING.md
- Documentation/Hackers-Guide
- dist.ini
- lib/Finance/Quote.pm
- lib/Finance/Quote/FTfunds.pm
- lib/Finance/Quote/OnVista.pm
The tests t/04-critic.t and t/05-data-dumper.t were failing if enabled by setting TEST_AUTHOR.
This PR made some minor edits to correct this.
> Changes to address TEST_AUTHOR failures.

- Changes
- Modules-README.yml
- lib/Finance/Quote/BorsaItaliana.pm
Added code to check for a proper trade date.
Will close #528
> Handle bad date in BorsaItaliana.pm
